/*
  Next.js is a React-based framework designed to build fast, server-rendered web applications with ease.
  In Next.js, the folder and file structure in the src/app directory directly define the routes for the application.
  Each file named page.js inside a folder represents a route. For example:
  src/app/layout.js → Layout applied to all routes. Define a global structure and provide a shared wrraper for all pages. 
  src/app/mountain/page.js → Defines the route /mountain.
*/
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";  //Here we import Link. The Link as the name suggest is for adding links to the page. 

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

/*
  In the header component we create 2 links. 
  'Snowtooth Mountain' - localhost:3000/
  'Mountain Info' - localhost:3000/mountain 
 */
function Header() {
  return (
    <header>
      <div>
        <nav>
          <div>
            <Link href="/">Snowtooth Mountain</Link>
          </div>
          <div>
            <Link href="/mountain">Mountain Info</Link>
          </div>
        </nav>
      </div>
    </header>
  );
}

/*
  This is the actual wrraper for all pages. 
  So all pages will display the Header component. 
  The children prop is for rendering content if page.js exist for / (In our case thats what displays "More React to Come")
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
